sonar.projectKey=notes-app-sonar
sonar.projectName=notes-app-sonar
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/loadtest/**,**/venv/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.organization=wiraaja01
